# Generated by Django 4.1.7 on 2023-03-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='author',
        ),
        migrations.AddField(
            model_name='bot',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
