# Generated by Django 4.1.7 on 2023-03-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_rename_author_bot_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='author_id',
            new_name='author',
        ),
    ]
