# Generated by Django 4.1.7 on 2023-03-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_rename_author_id_bot_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='author',
        ),
    ]
